# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsscript',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='jsscript',
            name='book_name',
        ),
        migrations.AlterField(
            model_name='jsscript',
            name='updatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
